#!/bin/bash


function usage() {
  echo "Usage: ${0} ⟨command sequence⟩" 1>&2
  exit ${1}
}

# check that some arguments habe been passed
if [ ${#} -eq 1 ]; then
  usage 1;
else
  javac MyGit.java
  java MyGit ${@:2}