#!/bin/bash

function usage() {
  echo "Usage: ${0} ⟨command sequence⟩" 1>&2
  exit ${1}
}

# basic help function to see usage
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  usage 0;
else
  # compile and run MyGit.java with every argument passed.
  # ${@:1} excludes './mygit' from args 
  javac MyGit.java
  java MyGit ${@:1}
fi
